# db-primary, recreated with the rotated value
apiVersion: v1
kind: Secret
metadata:
  name: db-primary
type: Opaque
immutable: true   # ALL THAT CRASHING OUT BECAUSE OF THIS DAMN FIELD LOL!!
stringData:
  API_KEY: primary-key-123      # NEED TO DELETE THE SECRET OBJECT AND RECREATE WITH NEW VALUE THIS ONE CRASHED ME OUT LOOL!!