apiVersion: v1
kind: ConfigMap
metadata:
  name: app-settings
data:
  app.conf: "Hello" # Each Key Becomes a File when mounted as a Volume! so key needs to be name app.conf because we are reading that file in Original Pod Manifest