apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  LOG_LEVEL: "debug"
  MAX_CONNECTIONS: "100" # I messed up here even tho the value is int it should be wrapped in "" else it will throw a hard to catch error unless u use online yml validators... lol
  app.properties: |
    timeout=30
    retries=3