apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
    - name: demo-container
      image: busybox:1.25
      command: ["sleep", "3600"]
      env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: DB_PASS
      volumeMounts:
        - name: secret-mnt
          mountPath: /home/db   # Trying to mount as a file
  volumes:
    - name: secret-mnt
      secret:
        secretName: db-creds