apiVersion: v1
kind: Pod
metadata:
  name: vol-s1-pod
  labels:
    app: mypod
spec:
  containers:
  - name: myapp
    image: nginx:alpine
    ports:
      - containerPort: 80
    volumeMounts:
      - name: data-vol
        mountPath: /usr/share/nginx/html
  volumes:
    - name: data-vol
      emptyDir: {}
