apiVersion: v1
kind: Pod
metadata:
  name: vol-s2-pod
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
    - name: host-logs
      mountPath: /app/logs
  volumes:
  - name: host-logs
    hostPath:
      path: /opt/strict-logs
      type: DirectoryOrCreate       # 'Directory' just checks for the dir in host if it doesnt exist then it just throws an error but DirectoryOrCreate created the dir if it doesnt exist and can only throw err is its not able to create...

# Additional Notes If you arent able to see the directory created by DirectoryOrCreate option check 'k get pods -o wide' check where the pod is scheduled and run ls /path/to/dir on that node : )