# s2_pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-2
spec:
  containers:
    - name: demo-container
      image: busybox:1.25
      command: ["sh", "-c", "echo DB_PASS=$DB_PASS && sleep 3600"]
      env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-creds-v1
              key: DB_PASS